export default {
    LATEST_MOVIES: 'LATEST_MOVIES',
    FAVORITE_MOVIES: 'FAVORITE_MOVIES',
    MOVIES_REQUEST: 'MOVIES_REQUEST',

    LATEST_MOVIES_RESPONSE: 'LATEST_MOVIES_RESPONSE',
    FAVORITE_MOVIES_RESPONSE: 'FAVORITE_MOVIES_RESPONSE',

    SAVE_FAVORITE_MOVIES_TO_LOCALSTORE: 'SAVE_FAVORITE_MOVIES_TO_LOCALSTORE',
    SET_MOVIE_TO_FAVORITE: 'SET_MOVIE_TO_FAVORITE',
    UNSET_MOVIE_FROM_FAVORITE: 'UNSET_MOVIE_FROM_FAVORITE',
}